app: opsapi-kisaan

env: CICD_NAMESPACE_PLACEHOLDER

image:
  repository: bwalia/opsapi
  tag: latest
  pullPolicy: Always

app_secrets:
    database_host: DATABASE_HOST 
    database_port: DATABASE_PORT
    database_user: DATABASE_USER
    database_password: DATABASE_PASSWORD
    database_name: DATABASE_NAME
    jwt_secret_key: JWT_SECRET_KEY
    keycloak_auth_url: KEYCLOAK_AUTH_URL
    keycloak_client_id: KEYCLOAK_CLIENT_ID
    keycloak_client_secret: KEYCLOAK_CLIENT_SECRET
    keycloak_redirect_uri: KEYCLOAK_REDIRECT_URI
    keycloak_token_url: KEYCLOAK_TOKEN_URL
    keycloak_userinfo_url: KEYCLOAK_USERINFO_URL
    lapis_config_lua_file: LAPIS_CONFIG_LUA_FILE
    minio_access_key: MINIO_ACCESS_KEY
    minio_bucket: MINIO_BUCKET
    minio_endpoint: MINIO_ENDPOINT
    minio_region: MINIO_REGION
    minio_secret_key: MINIO_SECRET_KEY
    node_api_url: NODE_API_URL
    openssl_secret_iv: OPENSSL_SECRET_IV
    openssl_secret_key: OPENSSL_SECRET_KEY
    google_client_id: GOOGLE_CLIENT_ID
    google_client_secret: GOOGLE_CLIENT_SECRET
    google_redirect_uri: GOOGLE_REDIRECT_URI
    stripe_secret_key: STRIPE_SECRET_KEY
    stripe_publishable_key: STRIPE_PUBLISHABLE_KEY
    stripe_webhook_secret: STRIPE_WEBHOOK_SECRET
    next_public_api_url: NEXT_PUBLIC_API_URL

replicaCount: 1

service:
  name: opsapi-kisaan-svc
  type: ClusterIP
  port: 80

svcAccessPort: CICD_SVC_PORT_PLACEHOLDER

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: CICD_NAMESPACE_PLACEHOLDER-api.kisaan.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
