apiVersion: v1
data:
  DATABASE_NAME: DATABASE_NAME_BASE64
  DATABASE_HOST: DATABASE_HOST_BASE64
  DATABASE_PASSWORD: DATABASE_PASSWORD_BASE64
  DATABASE_PORT: DATABASE_PORT_BASE64
  DATABASE_USER: DATABASE_USER_BASE64
  JWT_SECRET_KEY: JWT_SECRET_KEY_BASE64
  KEYCLOAK_AUTH_URL: KEYCLOAK_AUTH_URL_BASE64
  KEYCLOAK_CLIENT_ID: KEYCLOAK_CLIENT_ID_BASE64
  KEYCLOAK_CLIENT_SECRET: KEYCLOAK_CLIENT_SECRET_BASE64
  KEYCLOAK_REDIRECT_URI: KEYCLOAK_REDIRECT_URI_BASE64
  KEYCLOAK_TOKEN_URL: KEYCLOAK_TOKEN_URL_BASE64
  KEYCLOAK_USERINFO_URL: KEYCLOAK_USERINFO_URL_BASE64
  LAPIS_CONFIG_LUA_FILE: LAPIS_CONFIG_LUA_FILE_BASE64
  MINIO_ACCESS_KEY: MINIO_ACCESS_KEY_BASE64
  MINIO_BUCKET: MINIO_BUCKET_BASE64
  MINIO_ENDPOINT: MINIO_ENDPOINT_BASE64
  MINIO_SECRET_KEY: MINIO_SECRET_KEY_BASE64
  OPENSSL_SECRET_IV: OPENSSL_SECRET_IV_BASE64
  OPENSSL_SECRET_KEY: OPENSSL_SECRET_KEY_BASE64
  MINIO_REGION: MINIO_REGION_BASE64
  NODE_API_URL: NODE_API_URL_BASE64
kind: Secret
metadata:
  name: CICD_PROJECT_NAME-secrets
  namespace: CICD_NAMESPACE_PLACEHOLDER